name: PromotionEssentials
authors: [ethsmith]
version: 3.0.0-SNAPSHOT

depend: [Vault]

main: me.tekkitcommando.pe.PromotionEssentials

commands:
  apply:
    usage: /apply <password>
  token:
    usage: /token <token>
  rank:
    usage: /rank [subcommand]