name: PromotionEssentials
authors: [TekkitCommando]
version: 2.0.7

depend: [Vault]

main: me.tekkitcommando.promotionessentials.PromotionEssentials

commands:
  apply:
    usage: /apply <password>
  token:
    usage: /token <token>
  rank:
    usage: /rank [subcommand]